spring.application.name=Test

server.port=8081
server.servlet.context-path=/test

logging.level.root=debug

db.url=jdbc:mysql://192.168.0.100:3306/app_db
db.username=registerdb
db.password=@Hfg@36ySak
