spring.application.name=PRD

server.port=8082
server.servlet.context-path=/prd

logging.level.root=info

db.url=jdbc:mysql://192.168.0.100:3306/app_db
db.username=registerdbmain
db.password=jasASCDASK@@!$@12e21

